// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_api.proto

package com.avast.metrics.grpc;

public final class TestApiOuterClass {
  private TestApiOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TestApiOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TestApi)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code TestApi}
   */
  public  static final class TestApi extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TestApi)
      TestApiOrBuilder {
    // Use TestApi.newBuilder() to construct.
    private TestApi(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestApi() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TestApi(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.avast.metrics.grpc.TestApiOuterClass.internal_static_TestApi_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.avast.metrics.grpc.TestApiOuterClass.internal_static_TestApi_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.avast.metrics.grpc.TestApiOuterClass.TestApi.class, com.avast.metrics.grpc.TestApiOuterClass.TestApi.Builder.class);
    }

    public interface GetRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:TestApi.GetRequest)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       * REQUIRED
       * </pre>
       *
       * <code>repeated string names = 1;</code>
       */
      java.util.List<String>
          getNamesList();
      /**
       * <pre>
       * REQUIRED
       * </pre>
       *
       * <code>repeated string names = 1;</code>
       */
      int getNamesCount();
      /**
       * <pre>
       * REQUIRED
       * </pre>
       *
       * <code>repeated string names = 1;</code>
       */
      String getNames(int index);
      /**
       * <pre>
       * REQUIRED
       * </pre>
       *
       * <code>repeated string names = 1;</code>
       */
      com.google.protobuf.ByteString
          getNamesBytes(int index);
    }
    /**
     * Protobuf type {@code TestApi.GetRequest}
     */
    public  static final class GetRequest extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:TestApi.GetRequest)
        GetRequestOrBuilder {
      // Use GetRequest.newBuilder() to construct.
      private GetRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private GetRequest() {
        names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private GetRequest(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();
                if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                  names_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000001;
                }
                names_.add(s);
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
            names_ = names_.getUnmodifiableView();
          }
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.avast.metrics.grpc.TestApiOuterClass.internal_static_TestApi_GetRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.avast.metrics.grpc.TestApiOuterClass.internal_static_TestApi_GetRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest.class, com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest.Builder.class);
      }

      public static final int NAMES_FIELD_NUMBER = 1;
      private com.google.protobuf.LazyStringList names_;
      /**
       * <pre>
       * REQUIRED
       * </pre>
       *
       * <code>repeated string names = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getNamesList() {
        return names_;
      }
      /**
       * <pre>
       * REQUIRED
       * </pre>
       *
       * <code>repeated string names = 1;</code>
       */
      public int getNamesCount() {
        return names_.size();
      }
      /**
       * <pre>
       * REQUIRED
       * </pre>
       *
       * <code>repeated string names = 1;</code>
       */
      public String getNames(int index) {
        return names_.get(index);
      }
      /**
       * <pre>
       * REQUIRED
       * </pre>
       *
       * <code>repeated string names = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNamesBytes(int index) {
        return names_.getByteString(index);
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        for (int i = 0; i < names_.size(); i++) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, names_.getRaw(i));
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        {
          int dataSize = 0;
          for (int i = 0; i < names_.size(); i++) {
            dataSize += computeStringSizeNoTag(names_.getRaw(i));
          }
          size += dataSize;
          size += 1 * getNamesList().size();
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest)) {
          return super.equals(obj);
        }
        com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest other = (com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest) obj;

        boolean result = true;
        result = result && getNamesList()
            .equals(other.getNamesList());
        return result;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getNamesCount() > 0) {
          hash = (37 * hash) + NAMES_FIELD_NUMBER;
          hash = (53 * hash) + getNamesList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code TestApi.GetRequest}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:TestApi.GetRequest)
          com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.avast.metrics.grpc.TestApiOuterClass.internal_static_TestApi_GetRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.avast.metrics.grpc.TestApiOuterClass.internal_static_TestApi_GetRequest_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest.class, com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest.Builder.class);
        }

        // Construct using com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.avast.metrics.grpc.TestApiOuterClass.internal_static_TestApi_GetRequest_descriptor;
        }

        public com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest getDefaultInstanceForType() {
          return com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest.getDefaultInstance();
        }

        public com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest build() {
          com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest buildPartial() {
          com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest result = new com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest(this);
          int from_bitField0_ = bitField0_;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            names_ = names_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.names_ = names_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest) {
            return mergeFrom((com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest other) {
          if (other == com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest.getDefaultInstance()) return this;
          if (!other.names_.isEmpty()) {
            if (names_.isEmpty()) {
              names_ = other.names_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNamesIsMutable();
              names_.addAll(other.names_);
            }
            onChanged();
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private com.google.protobuf.LazyStringList names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureNamesIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            names_ = new com.google.protobuf.LazyStringArrayList(names_);
            bitField0_ |= 0x00000001;
           }
        }
        /**
         * <pre>
         * REQUIRED
         * </pre>
         *
         * <code>repeated string names = 1;</code>
         */
        public com.google.protobuf.ProtocolStringList
            getNamesList() {
          return names_.getUnmodifiableView();
        }
        /**
         * <pre>
         * REQUIRED
         * </pre>
         *
         * <code>repeated string names = 1;</code>
         */
        public int getNamesCount() {
          return names_.size();
        }
        /**
         * <pre>
         * REQUIRED
         * </pre>
         *
         * <code>repeated string names = 1;</code>
         */
        public String getNames(int index) {
          return names_.get(index);
        }
        /**
         * <pre>
         * REQUIRED
         * </pre>
         *
         * <code>repeated string names = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNamesBytes(int index) {
          return names_.getByteString(index);
        }
        /**
         * <pre>
         * REQUIRED
         * </pre>
         *
         * <code>repeated string names = 1;</code>
         */
        public Builder setNames(
            int index, String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureNamesIsMutable();
          names_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <pre>
         * REQUIRED
         * </pre>
         *
         * <code>repeated string names = 1;</code>
         */
        public Builder addNames(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureNamesIsMutable();
          names_.add(value);
          onChanged();
          return this;
        }
        /**
         * <pre>
         * REQUIRED
         * </pre>
         *
         * <code>repeated string names = 1;</code>
         */
        public Builder addAllNames(
            Iterable<String> values) {
          ensureNamesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, names_);
          onChanged();
          return this;
        }
        /**
         * <pre>
         * REQUIRED
         * </pre>
         *
         * <code>repeated string names = 1;</code>
         */
        public Builder clearNames() {
          names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <pre>
         * REQUIRED
         * </pre>
         *
         * <code>repeated string names = 1;</code>
         */
        public Builder addNamesBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          ensureNamesIsMutable();
          names_.add(value);
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:TestApi.GetRequest)
      }

      // @@protoc_insertion_point(class_scope:TestApi.GetRequest)
      private static final com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest();
      }

      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<GetRequest>
          PARSER = new com.google.protobuf.AbstractParser<GetRequest>() {
        public GetRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new GetRequest(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<GetRequest> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<GetRequest> getParserForType() {
        return PARSER;
      }

      public com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface GetResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:TestApi.GetResponse)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       * REQUIRED
       * </pre>
       *
       * <code>map&lt;string, int32&gt; results = 1;</code>
       */
      int getResultsCount();
      /**
       * <pre>
       * REQUIRED
       * </pre>
       *
       * <code>map&lt;string, int32&gt; results = 1;</code>
       */
      boolean containsResults(
              String key);
      /**
       * Use {@link #getResultsMap()} instead.
       */
      @Deprecated
      java.util.Map<String, Integer>
      getResults();
      /**
       * <pre>
       * REQUIRED
       * </pre>
       *
       * <code>map&lt;string, int32&gt; results = 1;</code>
       */
      java.util.Map<String, Integer>
      getResultsMap();
      /**
       * <pre>
       * REQUIRED
       * </pre>
       *
       * <code>map&lt;string, int32&gt; results = 1;</code>
       */

      int getResultsOrDefault(
              String key,
              int defaultValue);
      /**
       * <pre>
       * REQUIRED
       * </pre>
       *
       * <code>map&lt;string, int32&gt; results = 1;</code>
       */

      int getResultsOrThrow(
              String key);
    }
    /**
     * Protobuf type {@code TestApi.GetResponse}
     */
    public  static final class GetResponse extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:TestApi.GetResponse)
        GetResponseOrBuilder {
      // Use GetResponse.newBuilder() to construct.
      private GetResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private GetResponse() {
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private GetResponse(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                  results_ = com.google.protobuf.MapField.newMapField(
                      ResultsDefaultEntryHolder.defaultEntry);
                  mutable_bitField0_ |= 0x00000001;
                }
                com.google.protobuf.MapEntry<String, Integer>
                results__ = input.readMessage(
                    ResultsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                results_.getMutableMap().put(
                    results__.getKey(), results__.getValue());
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.avast.metrics.grpc.TestApiOuterClass.internal_static_TestApi_GetResponse_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetResults();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.avast.metrics.grpc.TestApiOuterClass.internal_static_TestApi_GetResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse.class, com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse.Builder.class);
      }

      public static final int RESULTS_FIELD_NUMBER = 1;
      private static final class ResultsDefaultEntryHolder {
        static final com.google.protobuf.MapEntry<
            String, Integer> defaultEntry =
                com.google.protobuf.MapEntry
                .<String, Integer>newDefaultInstance(
                    com.avast.metrics.grpc.TestApiOuterClass.internal_static_TestApi_GetResponse_ResultsEntry_descriptor,
                    com.google.protobuf.WireFormat.FieldType.STRING,
                    "",
                    com.google.protobuf.WireFormat.FieldType.INT32,
                    0);
      }
      private com.google.protobuf.MapField<
          String, Integer> results_;
      private com.google.protobuf.MapField<String, Integer>
      internalGetResults() {
        if (results_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ResultsDefaultEntryHolder.defaultEntry);
        }
        return results_;
      }

      public int getResultsCount() {
        return internalGetResults().getMap().size();
      }
      /**
       * <pre>
       * REQUIRED
       * </pre>
       *
       * <code>map&lt;string, int32&gt; results = 1;</code>
       */

      public boolean containsResults(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetResults().getMap().containsKey(key);
      }
      /**
       * Use {@link #getResultsMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, Integer> getResults() {
        return getResultsMap();
      }
      /**
       * <pre>
       * REQUIRED
       * </pre>
       *
       * <code>map&lt;string, int32&gt; results = 1;</code>
       */

      public java.util.Map<String, Integer> getResultsMap() {
        return internalGetResults().getMap();
      }
      /**
       * <pre>
       * REQUIRED
       * </pre>
       *
       * <code>map&lt;string, int32&gt; results = 1;</code>
       */

      public int getResultsOrDefault(
          String key,
          int defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, Integer> map =
            internalGetResults().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * REQUIRED
       * </pre>
       *
       * <code>map&lt;string, int32&gt; results = 1;</code>
       */

      public int getResultsOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, Integer> map =
            internalGetResults().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        com.google.protobuf.GeneratedMessageV3
          .serializeStringMapTo(
            output,
            internalGetResults(),
            ResultsDefaultEntryHolder.defaultEntry,
            1);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (java.util.Map.Entry<String, Integer> entry
             : internalGetResults().getMap().entrySet()) {
          com.google.protobuf.MapEntry<String, Integer>
          results__ = ResultsDefaultEntryHolder.defaultEntry.newBuilderForType()
              .setKey(entry.getKey())
              .setValue(entry.getValue())
              .build();
          size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(1, results__);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse)) {
          return super.equals(obj);
        }
        com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse other = (com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse) obj;

        boolean result = true;
        result = result && internalGetResults().equals(
            other.internalGetResults());
        return result;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (!internalGetResults().getMap().isEmpty()) {
          hash = (37 * hash) + RESULTS_FIELD_NUMBER;
          hash = (53 * hash) + internalGetResults().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code TestApi.GetResponse}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:TestApi.GetResponse)
          com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.avast.metrics.grpc.TestApiOuterClass.internal_static_TestApi_GetResponse_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMapField(
            int number) {
          switch (number) {
            case 1:
              return internalGetResults();
            default:
              throw new RuntimeException(
                  "Invalid map field number: " + number);
          }
        }
        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMutableMapField(
            int number) {
          switch (number) {
            case 1:
              return internalGetMutableResults();
            default:
              throw new RuntimeException(
                  "Invalid map field number: " + number);
          }
        }
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.avast.metrics.grpc.TestApiOuterClass.internal_static_TestApi_GetResponse_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse.class, com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse.Builder.class);
        }

        // Construct using com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          internalGetMutableResults().clear();
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.avast.metrics.grpc.TestApiOuterClass.internal_static_TestApi_GetResponse_descriptor;
        }

        public com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse getDefaultInstanceForType() {
          return com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse.getDefaultInstance();
        }

        public com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse build() {
          com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse buildPartial() {
          com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse result = new com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse(this);
          int from_bitField0_ = bitField0_;
          result.results_ = internalGetResults();
          result.results_.makeImmutable();
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse) {
            return mergeFrom((com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse other) {
          if (other == com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse.getDefaultInstance()) return this;
          internalGetMutableResults().mergeFrom(
              other.internalGetResults());
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private com.google.protobuf.MapField<
            String, Integer> results_;
        private com.google.protobuf.MapField<String, Integer>
        internalGetResults() {
          if (results_ == null) {
            return com.google.protobuf.MapField.emptyMapField(
                ResultsDefaultEntryHolder.defaultEntry);
          }
          return results_;
        }
        private com.google.protobuf.MapField<String, Integer>
        internalGetMutableResults() {
          onChanged();;
          if (results_ == null) {
            results_ = com.google.protobuf.MapField.newMapField(
                ResultsDefaultEntryHolder.defaultEntry);
          }
          if (!results_.isMutable()) {
            results_ = results_.copy();
          }
          return results_;
        }

        public int getResultsCount() {
          return internalGetResults().getMap().size();
        }
        /**
         * <pre>
         * REQUIRED
         * </pre>
         *
         * <code>map&lt;string, int32&gt; results = 1;</code>
         */

        public boolean containsResults(
            String key) {
          if (key == null) { throw new NullPointerException(); }
          return internalGetResults().getMap().containsKey(key);
        }
        /**
         * Use {@link #getResultsMap()} instead.
         */
        @Deprecated
        public java.util.Map<String, Integer> getResults() {
          return getResultsMap();
        }
        /**
         * <pre>
         * REQUIRED
         * </pre>
         *
         * <code>map&lt;string, int32&gt; results = 1;</code>
         */

        public java.util.Map<String, Integer> getResultsMap() {
          return internalGetResults().getMap();
        }
        /**
         * <pre>
         * REQUIRED
         * </pre>
         *
         * <code>map&lt;string, int32&gt; results = 1;</code>
         */

        public int getResultsOrDefault(
            String key,
            int defaultValue) {
          if (key == null) { throw new NullPointerException(); }
          java.util.Map<String, Integer> map =
              internalGetResults().getMap();
          return map.containsKey(key) ? map.get(key) : defaultValue;
        }
        /**
         * <pre>
         * REQUIRED
         * </pre>
         *
         * <code>map&lt;string, int32&gt; results = 1;</code>
         */

        public int getResultsOrThrow(
            String key) {
          if (key == null) { throw new NullPointerException(); }
          java.util.Map<String, Integer> map =
              internalGetResults().getMap();
          if (!map.containsKey(key)) {
            throw new IllegalArgumentException();
          }
          return map.get(key);
        }

        public Builder clearResults() {
          internalGetMutableResults().getMutableMap()
              .clear();
          return this;
        }
        /**
         * <pre>
         * REQUIRED
         * </pre>
         *
         * <code>map&lt;string, int32&gt; results = 1;</code>
         */

        public Builder removeResults(
            String key) {
          if (key == null) { throw new NullPointerException(); }
          internalGetMutableResults().getMutableMap()
              .remove(key);
          return this;
        }
        /**
         * Use alternate mutation accessors instead.
         */
        @Deprecated
        public java.util.Map<String, Integer>
        getMutableResults() {
          return internalGetMutableResults().getMutableMap();
        }
        /**
         * <pre>
         * REQUIRED
         * </pre>
         *
         * <code>map&lt;string, int32&gt; results = 1;</code>
         */
        public Builder putResults(
            String key,
            int value) {
          if (key == null) { throw new NullPointerException(); }

          internalGetMutableResults().getMutableMap()
              .put(key, value);
          return this;
        }
        /**
         * <pre>
         * REQUIRED
         * </pre>
         *
         * <code>map&lt;string, int32&gt; results = 1;</code>
         */

        public Builder putAllResults(
            java.util.Map<String, Integer> values) {
          internalGetMutableResults().getMutableMap()
              .putAll(values);
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:TestApi.GetResponse)
      }

      // @@protoc_insertion_point(class_scope:TestApi.GetResponse)
      private static final com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse();
      }

      public static com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<GetResponse>
          PARSER = new com.google.protobuf.AbstractParser<GetResponse>() {
        public GetResponse parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new GetResponse(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<GetResponse> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<GetResponse> getParserForType() {
        return PARSER;
      }

      public com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.avast.metrics.grpc.TestApiOuterClass.TestApi)) {
        return super.equals(obj);
      }
      com.avast.metrics.grpc.TestApiOuterClass.TestApi other = (com.avast.metrics.grpc.TestApiOuterClass.TestApi) obj;

      boolean result = true;
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.avast.metrics.grpc.TestApiOuterClass.TestApi parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.avast.metrics.grpc.TestApiOuterClass.TestApi parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.avast.metrics.grpc.TestApiOuterClass.TestApi parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.avast.metrics.grpc.TestApiOuterClass.TestApi parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.avast.metrics.grpc.TestApiOuterClass.TestApi parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.avast.metrics.grpc.TestApiOuterClass.TestApi parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.avast.metrics.grpc.TestApiOuterClass.TestApi parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.avast.metrics.grpc.TestApiOuterClass.TestApi parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.avast.metrics.grpc.TestApiOuterClass.TestApi parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.avast.metrics.grpc.TestApiOuterClass.TestApi parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.avast.metrics.grpc.TestApiOuterClass.TestApi parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.avast.metrics.grpc.TestApiOuterClass.TestApi parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.avast.metrics.grpc.TestApiOuterClass.TestApi prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TestApi}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TestApi)
        com.avast.metrics.grpc.TestApiOuterClass.TestApiOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.avast.metrics.grpc.TestApiOuterClass.internal_static_TestApi_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.avast.metrics.grpc.TestApiOuterClass.internal_static_TestApi_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.avast.metrics.grpc.TestApiOuterClass.TestApi.class, com.avast.metrics.grpc.TestApiOuterClass.TestApi.Builder.class);
      }

      // Construct using com.avast.metrics.grpc.TestApiOuterClass.TestApi.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.avast.metrics.grpc.TestApiOuterClass.internal_static_TestApi_descriptor;
      }

      public com.avast.metrics.grpc.TestApiOuterClass.TestApi getDefaultInstanceForType() {
        return com.avast.metrics.grpc.TestApiOuterClass.TestApi.getDefaultInstance();
      }

      public com.avast.metrics.grpc.TestApiOuterClass.TestApi build() {
        com.avast.metrics.grpc.TestApiOuterClass.TestApi result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.avast.metrics.grpc.TestApiOuterClass.TestApi buildPartial() {
        com.avast.metrics.grpc.TestApiOuterClass.TestApi result = new com.avast.metrics.grpc.TestApiOuterClass.TestApi(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.avast.metrics.grpc.TestApiOuterClass.TestApi) {
          return mergeFrom((com.avast.metrics.grpc.TestApiOuterClass.TestApi)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.avast.metrics.grpc.TestApiOuterClass.TestApi other) {
        if (other == com.avast.metrics.grpc.TestApiOuterClass.TestApi.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.avast.metrics.grpc.TestApiOuterClass.TestApi parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.avast.metrics.grpc.TestApiOuterClass.TestApi) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:TestApi)
    }

    // @@protoc_insertion_point(class_scope:TestApi)
    private static final com.avast.metrics.grpc.TestApiOuterClass.TestApi DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.avast.metrics.grpc.TestApiOuterClass.TestApi();
    }

    public static com.avast.metrics.grpc.TestApiOuterClass.TestApi getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestApi>
        PARSER = new com.google.protobuf.AbstractParser<TestApi>() {
      public TestApi parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TestApi(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestApi> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TestApi> getParserForType() {
      return PARSER;
    }

    public com.avast.metrics.grpc.TestApiOuterClass.TestApi getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  /**
   * Protobuf service {@code TestApiService}
   */
  public static abstract class TestApiService
      implements com.google.protobuf.Service {
    protected TestApiService() {}

    public interface Interface {
      /**
       * <code>rpc Get(.TestApi.GetRequest) returns (.TestApi.GetResponse);</code>
       */
      public abstract void get(
              com.google.protobuf.RpcController controller,
              com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest request,
              com.google.protobuf.RpcCallback<com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new TestApiService() {
        @Override
        public  void get(
            com.google.protobuf.RpcController controller,
            com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest request,
            com.google.protobuf.RpcCallback<com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse> done) {
          impl.get(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.get(controller, (com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest)request);
            default:
              throw new AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest.getDefaultInstance();
            default:
              throw new AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse.getDefaultInstance();
            default:
              throw new AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc Get(.TestApi.GetRequest) returns (.TestApi.GetResponse);</code>
     */
    public abstract void get(
        com.google.protobuf.RpcController controller,
        com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest request,
        com.google.protobuf.RpcCallback<com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.avast.metrics.grpc.TestApiOuterClass.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.get(controller, (com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest)request,
            com.google.protobuf.RpcUtil.<com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse>specializeCallback(
              done));
          return;
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest.getDefaultInstance();
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse.getDefaultInstance();
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.avast.metrics.grpc.TestApiOuterClass.TestApiService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void get(
          com.google.protobuf.RpcController controller,
          com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest request,
          com.google.protobuf.RpcCallback<com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse.class,
            com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse get(
              com.google.protobuf.RpcController controller,
              com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse get(
          com.google.protobuf.RpcController controller,
          com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.avast.metrics.grpc.TestApiOuterClass.TestApi.GetResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:TestApiService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestApi_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestApi_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestApi_GetRequest_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestApi_GetRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestApi_GetResponse_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestApi_GetResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestApi_GetResponse_ResultsEntry_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestApi_GetResponse_ResultsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016test_api.proto\"\231\001\n\007TestApi\032\033\n\nGetReque" +
      "st\022\r\n\005names\030\001 \003(\t\032q\n\013GetResponse\0222\n\007resu" +
      "lts\030\001 \003(\0132!.TestApi.GetResponse.ResultsE" +
      "ntry\032.\n\014ResultsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005val" +
      "ue\030\002 \001(\005:\0028\0012D\n\016TestApiService\0222\n\003Get\022\023." +
      "TestApi.GetRequest\032\024.TestApi.GetResponse" +
      "\"\000B-\n(com.avast.viruslab.authenticator.t" +
      "estapi\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TestApi_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TestApi_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestApi_descriptor,
        new String[] { });
    internal_static_TestApi_GetRequest_descriptor =
      internal_static_TestApi_descriptor.getNestedTypes().get(0);
    internal_static_TestApi_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestApi_GetRequest_descriptor,
        new String[] { "Names", });
    internal_static_TestApi_GetResponse_descriptor =
      internal_static_TestApi_descriptor.getNestedTypes().get(1);
    internal_static_TestApi_GetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestApi_GetResponse_descriptor,
        new String[] { "Results", });
    internal_static_TestApi_GetResponse_ResultsEntry_descriptor =
      internal_static_TestApi_GetResponse_descriptor.getNestedTypes().get(0);
    internal_static_TestApi_GetResponse_ResultsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestApi_GetResponse_ResultsEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
