name: Release
on:
  push:
    branches: [ master ]
  release:
    types: [ published ]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 11
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Test
        run: sbt test
      - name: Release
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET_NEW }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE_NEW }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: sbt ci-release
